# Generated by Django 2.2.11 on 2022-02-02 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vc',
            name='created',
            field=models.BooleanField(default=False),
        ),
    ]
